### ISSUE TITLE
Pasta YAML

### ISSUE THREAD

**Issue by zouloux** [zouloux/pasta#2]
Allow publishing branches with glob :

```yaml
branches:
  _default:
    ...
  preview:
    ...
  main:
    ...
  feature/*
    domain: $project_$1
```

Pushing `feature/test-home-page` will push to `${project}_test-home-page.$PASTA_DOMAIN`
